### ISSUE TITLE
PowerSynchronizer even operate if they are disabled.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.manager#57]
This issue seems to be again an result of changing the ActivatiableUnitController behavior.

**Comment by pLeminoq** [comment]
This issue is not related to the ActivatableUnitController but a bug in the PowerStateSynchrnoiserAgent itself. After recent changes where the agent has been adapted to observer requested power states the stop method has not been adapted. Thus observers where not removed correctly. This has been fixed in commit:

* 237b3a6ceffb6acbdded0b454e5a51194c23c047
